---
micronaut:
  application:
    name: crud-micronaut-kotlin

---

endpoints:
  all:
    enabled: true
    sensitive: false

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'

